### ISSUE TITLE
Error running Rubocop Error: Process execution timed out

### ISSUE THREAD

**Issue by TheJayWright** [AtomLinter/linter-rubocop#234] opened 2017-08-25 14:25 UTC
I just started receiving the error yesterday in Atom.

I'm running Mac OS X.

Error running RuboCop Error: Process execution timed out at /Users/myuser/.atom/packages/linter-rubocop/node_modules/sb-exec/lib/index.js:89:18
(anonymous) @ /Users/myuser/.atom/packages/linter/lib/linter-registry.js:159

**Comment by gluons** [comment] 2017-08-26 17:06
Me too. Also face this issue.

Running on **Atom 1.19.3** on **Kubuntu 17.04**

**Comment by gluons** [comment] 2017-08-26 17:12
Oh! Maybe duplicate of #202.

I found the solution.
Just find the absolute path of `rubocop` by `which rubocop` and set it in settings.

**Comment by TheJayWright** [comment] 2017-08-27 04:26
I tried that with no success, however I reinstalled the rubocop gem and reinstalled the Atom package and have had success.

**Comment by maschwenk** [comment] 2017-08-27 07:13
Indeed a duplicate of #202 . I've had some thoughts in the past of ways to trap errors like these and suggest changing the rubocop path but never quite got to it

**Comment by maschwenk** [comment] 2017-08-27 07:14
Indeed a duplicate of #202 . I've had some thoughts in the past of ways to trap errors like these and suggest changing the rubocop path but never quite got to it

**Closed by maschwenk** 2017-08-27 07:14 UTC
