### ISSUE TITLE
Uncaught Error: spawn EACCES 

### ISSUE THREAD

**Issue by timscott** [AtomLinter/linter-rubocop#6] opened 2014-06-16 14:30 UTC
Just upgraded to 0.103.0 of Atom. Now, whenever I open a `.rb` file I get this error:

```
Uncaught Error: spawn EACCES util.js:682
  exports._errnoException util.js:682
  ChildProcess.spawn child_process.js:1017
  exports.spawn child_process.js:801
  BufferedProcess /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:25
  Linter.lintFile linter.coffee:114
  (anonymous function) linter-view.coffee:133
  (anonymous function) fs.js:97
```

**Comment by acrogenesis** [comment] 2015-08-07 23:01
I also get this I'm on rvm

**Comment by ricsdeol** [comment] 2015-08-10 13:08
The problem happened always on save file.

**Atom Version**: 1.0.3
**System**: elementary OS
**Thrown From**: [linter-rubocop](https://github.com/AtomLinter/linter-rubocop) package, v0.3.1
**Ruby**: RVM (1.26.11)


### Stack Trace

Uncaught Error: spawn EACCES

```
At /opt/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/ricardoleite/.atom/packages/linter-rubocop/index.coffee:27:9
  at /home/ricardoleite/.atom/packages/linter-haml/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-erb",
      "atom-ctags",
      "autocomplete-elixir"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/ricardoleite/src"
  },
  "linter-rubocop": {
    "rubocopExecutablePath": "/home/ricardoleite/.rvm/gems/ruby-2.1.6/bin/rubocop",
    "executablePath": "/home/ricardoleite/.rvm/gems/ruby-2.1.6/bin/"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-zeal, v0.1.3
atomatigit, v1.5.4
autocomplete-ctags, v0.3.1
autocomplete-haskell, v0.4.5
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v2.0.11
css-snippets, v0.8.0
ctags-status, v1.3.3
docs-snippets, v0.8.0
file-icons, v1.6.3
git-log, v0.4.1
git-tab-status, v1.9.2
gulp-snippets, v0.6.1
haskell-ghc-mod, v0.8.8
html-id-class-snippets, v1.4.1
ide-haskell, v0.7.1
language-diff, v0.3.0
language-gitignore, v0.2.0
language-haskell, v1.3.0
language-txt2tags, v0.3.0
linter, v1.3.4
linter-coffeelint, v1.0.2
linter-haml, v1.0.0
linter-js-yaml, v1.1.1
linter-jshint, v1.1.5
linter-less, v2.0.3
linter-rubocop, v0.3.1
linter-ruby, v1.0.0
linter-tidy, v1.0.1
local-history, v3.2.3
merge-conflicts, vundefined
minimap, v4.12.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-pigments, v0.1.3
minimap-selection, v4.3.0
pigments, v0.9.3
rspec-snippets, v0.4.0
ruby-block, v0.3.5
spotify-linux, v0.3.2
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
tab-smart-sort, v0.1.4
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-08-10 13:45
Just a sidenote: Node `EACCESS` error means that either the file you are accessing is inaccessible, if you are trying to execute it then it's not executable.

**Comment by ricsdeol** [comment] 2015-08-10 17:03
@steelbrain  my rubocop path:
```
-rwxr-xr-x 1 ricardoleite ricardoleite 514 Jul  7 09:36 /home/ricardoleite/.rvm/gems/ruby-2.1.6/bin/rubocop
```

**Comment by steelbrain** [comment] 2015-08-10 18:41
@ricsdeol Can you dump the value of `command` before this line and report what it is?
https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee#L27

**Comment by scashin133** [comment] 2015-08-10 19:06
I had to change my executable path to include rubocop in order for this to go away. 

from
```
/Users/scashin133/.rvm/gems/ruby-2.2.2@global/bin
```
to
```
/Users/scashin133/.rvm/gems/ruby-2.2.2@global/bin/rubocop
```

**Comment by egeland** [comment] 2015-08-12 01:50
@scashin133 - I also had to add `/rubocop` to the executable path, then the problem appears to have gone away.. Thanks for the work-around!

**Comment by hez** [comment] 2015-08-13 16:19
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-rubocop](https://github.com/AtomLinter/linter-rubocop) package, v0.3.1


### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/hez/.atom/packages/linter-rubocop/index.coffee:54:18
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false
  },
  "linter-rubocop": {
    "executablePath": "/usr/bin/"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.3.4
linter-rubocop, v0.3.1

# Dev
No dev packages

**Comment by acrogenesis** [comment] 2015-08-13 17:10
@hez is right, that fixed it!

**Comment by ricsdeol** [comment] 2015-08-18 16:52
><cite> Can you dump the value of command before this line and report what it is?
https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee#L27 </cite>

@steelbrain How I do this?

**Comment by jossemarGT** [comment] 2015-08-18 22:53
Sorry to bother but I'm still hitting the wall with this issue in atom 1.0.7, even with

```
  "linter-rubocop":
    ExecutablePath: "/Users/<user>/.rvm/gems/ruby-2.2.0/bin/rubocop"
````

**Comment by acrogenesis** [comment] 2015-08-19 18:46
@jossemarGT have you tried restarting atom? That fixed mine

**Comment by prokopsimek** [comment] 2016-12-21 09:29
+1

**Comment by jossemarGT** [comment] 2016-12-22 16:53
OMG I didn't see your mention @acrogenesis (kinda late to notice it), for future references it was my fault I didn't have rubocop into the project's gemset (installed by bundler).

**Comment by Arcanemagus** [comment] 2017-05-22 23:29
Marking this as closed, the original reporter _never_ responded, and this thread has gotten overly large with many different people's reports.

Generally this is caused by setting a _directory_ in the Executable Path setting, instead of the full path to `rubocop`. If you have verified that you aren't doing this and are still having problems please file a new issue, thanks!

**Closed by Arcanemagus** 2017-05-22 23:29 UTC
