### ISSUE TITLE
Not setting TargetRubyVersion using .ruby-version

### ISSUE THREAD

**Issue by aried3r** [AtomLinter/linter-rubocop#164] opened 2016-09-19 14:47 UTC
Since a few versions ago, rubocop [sets the `TargetRubyVersion` using the `.ruby-version`](http://rubocop.readthedocs.io/en/latest/configuration/#setting-the-target-ruby-version) file so you don't have to repeat yourself, when using something like rbenv or rvm.

It seems linter-rubocop does not respect that setting.

I'm starting atom via the command line using `atom .` which should load the right environment, the path to rubocop is set correctly (to the version installed using `rbenv which rubocop`).

I'm not quite sure if it's a problem with linter-rubocop, but I think so, since it respects all my rubocop settings except this one.

OSX 10.11.6
Atom 1.10.0
linter 1.11.16
linter-rubocop 0.4.7

**Comment by Arcanemagus** [comment] 2016-09-19 18:42
I wonder if `rubocop` isn't actually working _quite_ like it says, and instead uses the file path to determine where to look for that file? We are setting the working directory to that of the file [here](https://github.com/AtomLinter/linter-rubocop/blob/v0.4.7/index.coffee#L24), but the actual contents `rubocop` is running on are passed in via `stdin`.

**Comment by aried3r** [comment] 2016-09-19 18:47
Is there a way for me to check? Is there a verbose mode or something similar?

**Comment by Arcanemagus** [comment] 2016-09-19 23:15
You can open Atom's Developer Tools and place a breakpoint [here](https://github.com/AtomLinter/linter-rubocop/blob/v0.4.7/index.coffee#L26) and check the value of `cwd` to see where it is executing `rubocop` "from".

If you have a zip file of a folder that exhibits this I can try tracking it down, but I don't use `rubocop` myself.

**Comment by aried3r** [comment] 2016-09-23 13:34
Hmm, the `cwd` and `command` seem to be correct. I tried creating a simple ruby project but it showed none of the problems. I'll try to create a minimal rails project to see if I can reproduce it there.

**Comment by aried3r** [comment] 2016-10-06 16:32
[atom-linter-issue-164.zip](https://github.com/AtomLinter/linter-rubocop/files/514337/atom-linter-issue-164.zip)

Here is a zip file which contains a fresh Rails app with the latest linter-rubocop and Atom installed.

**Comment by aried3r** [comment] 2016-10-14 12:28
My coworker just reported the same problem. He's using Ubuntu.

**Comment by sLe1tner** [comment] 2016-10-14 12:35
> He's using Ubuntu.
Ubuntu 16.4
Atom 1.10.2
linter 1.11.16
linter-rubocop 0.4.7
Atom also started with `atom .`

**Comment by chrishough** [comment] 2016-12-31 23:33
Has anyone found a fix for this?

**Comment by maschwenk** [comment] 2017-03-11 19:58
Dupe of #195

**Closed by maschwenk** 2017-03-11 19:58 UTC
