### ISSUE TITLE
No warnings in Atom when using Rubocop in a Docker container because of --stdin

### ISSUE THREAD

**Issue by zedtux** [AtomLinter/linter-rubocop#245] opened 2017-10-09 13:11 UTC
I'm using a container which embeds rubocop and I'm using it in Atom.

Atom is not displaying any linter messages when opening a Ruby file, but the "Linter Rubocop: Fix file" is actually updating my source file.

Playing around in the source code of linter-rubocop made me remove the concat of `--stdin` which fixed my issue, and Atom started to show the lint messages.

I guess this is due to the use case of Docker so I would suggest then to add an option in the package which would prevent from using the `--stdin` flag so that you can keep the current behaviour but allow this use case to work too.

**Comment by zedtux** [comment] 2017-10-09 13:12
BTW I could do PR if you'd like to.

**Comment by maschwenk** [comment] 2017-10-09 19:34
We always encourage new contributors, have a go and I'll be happy to review 😃

**Comment by zedtux** [comment] 2017-10-09 20:45
Do you agree with this change?

**Comment by Arcanemagus** [comment] 2017-10-09 21:22
Double check what is going on here, I'm betting that you are only seeing messages for the on-disk contents of the file, not the contents coming in from `stdin` (the current editor contents).

**Comment by maschwenk** [comment] 2017-10-09 22:55
I read somewhere that you can also pass a filename to `--std-in` and it'll work, I'm not sure how that will affect the functionality of Rubocop in general though. Might lose on-the-fly linting?

**Comment by zedtux** [comment] 2017-10-10 05:36
I tried using `--stdin` with a file path and it's not doing any error, but is not seeing any offences while the file is full of them.

Doing exactly the same without `--stdin` make it just working.

I truly believe that `--stdin` has a particular behaviour requiring a kind of pipe with the IDE, which you don't have with Docker, or I don't know how to do it.

**Comment by Arcanemagus** [comment] 2017-10-10 17:03
What I meant was two-fold:

* Are you actually linting the live content without that flag
* Does removing that break _non_-Docker `rubocop`

> Might lose on-the-fly linting?

This is exactly the problem I'm worried about.

**Comment by zedtux** [comment] 2017-10-10 17:11
> Are you actually linting the live content without that flag

I don't because I think there is no pipes between the Atom instance and Rubocop which leaves within a Docker container.

> Does removing that break non-Docker rubocop

Not in the way I implemented it as it is a checkbox that has to be checked to not pass the `--stdin` flag so that by default, the current behaviour is preserved.

**Comment by maschwenk** [comment] 2017-10-10 17:17
I'm curious how you're actually using this? Are you using `docker-sync` or a similar system? Is it possible to edit files directly in the docker container without `docker exec` into the container?

**Comment by maschwenk** [comment] 2017-10-10 17:27
After talking to a colleague, I think you'll definitely lose the on the fly linting because without `std-in` I'm pretty sure it'll just lint the entire project. If you're ok with that I guess that's fine. It don't feel great about adding this option for a pretty fringe use case but I can get over it.

**Comment by zedtux** [comment] 2017-10-10 17:34
> Are you using docker-sync or just mounting the volume?

I'm using docker-sync.

> After talking to a colleague, I think you'll definitely lose the on the fly linting because without std-in I'm pretty sure it'll just lint the entire project.

Well with the tests I did, I can tell that it is only linting the current file, not the entire project. [I did a Docker image for Rubocop](https://github.com/zedtux/docker-rubocop), and in the repo you can see that I'm telling people to create a bash script which is basically ignoring the `--stdin` flag, and then run the container.

This PR is actually solving the issue at the root.

Honestly I don't know what is the difference between asking rubocop to parse the given file, or parse the stdin, but when I running it manually (so using `docker run`, passing the same arguments, I can see the generated JSON which shows the amount of parsed files, which is of 1, and all the offences found.

**Comment by maschwenk** [comment] 2017-10-10 17:44
I appreciate the thorough description, I'm at work right now so I need to look at this later more deeply to make sure I understand it

**Comment by zedtux** [comment] 2017-10-10 17:55
Short update: I use docker-sync in my project, but not for Rubocop, sorry. I'm using a Docker volume to mount the `/Users` folder (lazy trick in order to handle the given path ... could be improved) and from here, Rubocop can access the file to be linted.

Please feel free to ask me whatever can help you to understand the use case, I'm available to check/fix/update anything to get this working :)

**Comment by zedtux** [comment] 2017-10-12 08:37
Just to give a little bit more details, here are the tests I did manually in a terminal (same commands than Atom is running in the end, just to see the output):

With the `--stdin`:

```shell
docker run --rm -v /Users:/Users --workdir / zedtux/docker-rubocop:0.50.0 --cache false --force-exclusion --format json --display-style-guide --stdin /Users/guillaumeh/Developments/company/project/app/models/reporting_document_template.rb
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-linux"},"files":[{"path":"sers/guillaumeh/Developments/company/project/app/models/reporting_document_template.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}%
```

Without the `--stdin`:

```shell
docker run --rm -v /Users:/Users --workdir / zedtux/docker-rubocop:0.50.0 --cache false --force-exclusion --format json --display-style-guide /Users/guillaumeh/Developments/company/project/app/models/reporting_document_template.rb
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-linux"},"files":[{"path":"sers/guillaumeh/Developments/company/project/app/models/reporting_document_template.rb","offenses":[{"severity":"convention","message":"Extra empty line detected at class body beginning. (https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies)","cop_name":"Layout/EmptyLinesAroundClassBody","corrected":false,"location":{"line":2,"column":1,"length":1}},{"severity":"convention","message":"Line is too long. [93/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)","cop_name":"Metrics/LineLength","corrected":false,"location":{"line":20,"column":81,"length":13}},{"severity":"convention","message":"Line is too long. [90/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)","cop_name":"Metrics/LineLength","corrected":false,"location":{"line":30,"column":81,"length":10}}]}],"summary":{"offense_count":3,"target_file_count":1,"inspected_file_count":1}}%
```

**Comment by Arcanemagus** [comment] 2017-10-23 17:17
You need to find some way of passing the `stdin` stream to the docker process, **not** just adding the `--stdin` flag. A few other people have reported success creating a wrapper script that handles this for them:
https://github.com/AtomLinter/linter-phpcs/issues/299#issuecomment-338346850

**Comment by quolpr** [comment] 2017-11-15 11:22
The problem is that docker don't want to work with stdin. I don't really know what is the problem, but I create such bash file:

```
#!/bin/bash
docker exec -it my_container rubocop "$@"
```

And docker show error:

> the input device is not a TTY

With just `-t` argument atom shows that Linter is timed out.

Also, some other info:

```
echo 'puts "hello"' | docker exec -t my_container rubocop --stdin
missing argument: --stdin
/bundle/gems/rubocop-0.51.0/lib/rubocop/options.rb:19:in `parse'
/bundle/gems/rubocop-0.51.0/lib/rubocop/cli.rb:27:in `run'
/bundle/gems/rubocop-0.51.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/bundle/gems/rubocop-0.51.0/bin/rubocop:12:in `<top (required)>'
/bundle/bin/rubocop:21:in `load'
/bundle/bin/rubocop:21:in `<main>'


echo 'puts "hello"' | docker exec -it my_container rubocop --stdin
the input device is not a TTY
```

**Comment by quolpr** [comment] 2017-11-15 11:24
So I come to conclusion, that the best way will be not to use `--stdin`:

```
#!/bin/bash

# Remove invalid arguments send by linter-rubocop
CMD_ARGS=""
for arg in $@
do
# -s stands for --stdin which prevent rubocop from working
[[ "$arg" == "--stdin" ]] && continue

if [ -f "$arg" ]
then
  CMD_ARGS="$CMD_ARGS ${arg#$PWD/}"
else
  CMD_ARGS="$CMD_ARGS $arg"
fi
done
echo $CMD_ARGS

docker exec  my_conteiner rubocop $CMD_ARGS
```

But I am getting error at dev console :(

```
[Linter] Error running RuboCop Error: --cache false --force-exclusion --format json --display-style-guide app/helpers/download_helper.rb
{"metadata":{"rubocop_version":"0.51.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-linux"},"files":[{"path":"app/helpers/download_helper.rb","offenses":[{"severity":"convention","message":"Missing top-level module documentation comment.","cop_name":"Style/Documentation","corrected":false,"location":{"line":1,"column":1,"length":6}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
    at parseFromStd (index.js [sm]:23)
    at Object.<anonymous> (index.js [sm]:180)
    at Generator.next (<anonymous>)
    at step (/Users/quolpr/.atom/packages/linter-rubocop/src/index.js:11)
```

**Comment by quolpr** [comment] 2017-11-15 11:34
Oh, it was because of "echo"! So the right version is so:

```
#!/bin/bash

# Remove invalid arguments send by linter-rubocop
CMD_ARGS=""
for arg in $@
do
if [ -f "$arg" ]
then
  CMD_ARGS="$CMD_ARGS ${arg#$PWD/}"
else
  CMD_ARGS="$CMD_ARGS $arg"
fi
done

docker exec -i webshadowlanding_landing_1 rubocop $CMD_ARGS
```

**Comment by quolpr** [comment] 2017-11-15 11:36
Btw, why are you using absolute path? 🤔

**Comment by zedtux** [comment] 2017-11-15 12:44
@quolpr https://github.com/AtomLinter/linter-rubocop/issues/245#issuecomment-335555831

**Comment by quolpr** [comment] 2017-11-15 12:47
@zedtux so you can run rubocop without mounting /Users

**Comment by zedtux** [comment] 2017-11-15 13:12
Okay thank you @quolpr I will check that then. 👍

**Comment by Arcanemagus** [comment] 2018-01-16 17:45
Marking this as closed since this is _way_ outside the scope of this package and is (somewhat) easily solved by creating a wrapper script.

**Closed by Arcanemagus** 2018-01-16 17:45 UTC
Labels: External, question

**Comment by zedtux** [comment] 2018-01-16 17:59
Or at least something in the `README.md` people can copy/past and don't wast time.

**Comment by Arcanemagus** [comment] 2018-01-16 18:20
@zedtux Across dozens of repos and millions of downloads in the AtomLinter org there are _maybe_ 10 issues talking about Docker support, so making large changes to support it isn't exactly a high priority.

That being said, your #246 PR is a perfectly fine addition, I just recently reviewed it with some wording changes 😉.
