### ISSUE TITLE
Error: Gem.gunzip is deprecated

### ISSUE THREAD

**Issue by cpearce31** [AtomLinter/linter-rubocop#277] opened 2018-06-06 15:49 UTC
Getting the following error when opening `.rb` files in Atom on Ubuntu 18.04.
```
[Linter] Error running RuboCop Error: NOTE: Gem.gunzip is deprecated; use Gem::Util.gunzip instead. It will be removed on or after 2018-12-01.
Gem.gunzip called from /home/caleb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/unicode-display_width-1.3.0/lib/unicode/display_width/index.rb:5.
    at ChildProcess.<anonymous> (/home/caleb/.atom/packages/linter-eslint/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:899)
    at Socket.<anonymous> (internal/child_process.js:342)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at Pipe._handle.close [as _onclose] (net.js:510)
```

Versions:
- Atom: 1.26.1
- linter-rubocop: 2.2.3
- linter: 2.2.0
- ruby: 2.5.0

**Comment by Arcanemagus** [comment] 2018-06-06 15:54
Looks like this is a duplicate of https://github.com/janlelis/unicode-display_width/issues/17.

You can try updating that Gem in order to fix this issue. I'm closing this though as it has absolutely nothing to do with `linter-rubocop`.

Thanks for taking the time to file an issue!

**Closed by Arcanemagus** 2018-06-06 15:54 UTC

**Comment by sharkeyryan** [comment] 2018-06-20 19:04
This is a dependency of `rubocup` gem.

I added the following to my Gemfile and it fixed the issue:

`gem "unicode-display_width", ">= 1.3.3"`
