### ISSUE TITLE
Does not display warnings with Linter 1.3.0

### ISSUE THREAD

**Issue by lexi-lambda** [AtomLinter/linter-rubocop#55] opened 2015-08-03 17:46 UTC
Quite simply, it doesn't seem to do anything at all with `linter` 1.3.0. Everything works properly if I revert to 1.2.4.

**Comment by steelbrain** [comment] 2015-08-03 17:47
Dupe of https://github.com/AtomLinter/linter-rubocop/issues/50

**Closed by steelbrain** 2015-08-03 17:47 UTC
