### ISSUE TITLE
Error at index.coffee:30:15

### ISSUE THREAD

**Issue by skamansam** [AtomLinter/linter-rubocop#86] opened 2015-11-05 21:38 UTC
I get this every time I save a file (every time rubocop is run):

Error
  at /home/sam/.atom/packages/linter-rubocop/index.coffee:30:15

I am running atom 1.1.0 with rubocop 0.34.2

**Comment by caseywebdev** [comment] 2015-11-06 06:05
What happens when you run rubocop from the command line?

**Comment by freemanoid** [comment] 2015-11-08 18:14
I got similar error, it stated:
```
Error: env: ruby_executable_hooks: No such file or directory
at ~/.atom/packages/linter-rubocop/index.coffee:30:15
```
Atom 1.1.0, linter-rubocop 0.4.4

The problem is that I specified rubocop path as `~/.rvm/gems/ruby-2.1.2@global/bin/rubocop`.

I had to fix it to `~/.rvm/gems/ruby-2.1.2@global/wrappers/rubocop` (note the change from **bin** to **wrappers**). 

[Solution found at SO][1].
[1]: http://stackoverflow.com/questions/26247926/how-to-solve-usr-bin-env-ruby-executable-hooks-no-such-file-or-directory

**Comment by ckib16** [comment] 2015-11-30 19:25
Wow. THANK YOU @freemanoid ! I've been trying to get Rubocop running in Atom for a month and was about to give up. This solved it.

**Comment by johnmeehan** [comment] 2015-12-15 10:55
+1 for this! Thanks

**Comment by Arcanemagus** [comment] 2015-12-15 17:33
Marking this as closed since this is a configuration issue and not a problem with linter-rubocop. A PR explaining the issue for users of `rvm` in the readme would be appreciated though :wink:.

**Closed by Arcanemagus** 2015-12-15 17:33 UTC
